### ISSUE TITLE
Allow creating a new directory in file explorer and using current folders

### ISSUE THREAD

**Issue by mdibaiee** [theam/haskell-do#100]
Currently, it's not possible to create a new project in an already created folder, so the file explorer does not come as handy when it comes to creating a new project, they still have to write the path in the input.

I say we should have a button to create directories, and also, probably, use `stack new --bare` to create the project inside empty directories, or maybe we should also allow it in non-empty directories? Let's say one wants to transform his Haskell project to a HaskellDO project, is that possible at the moment @NickSeagull?

**Comment by NickSeagull** [comment]
Yes, it is not that handy.

Two persons had the button idea at the Zurihac too, which means that it is the good way to follow.

Also, it is not possible to transform regular haskell project into haskell.do projects right now, at least not automatically. It involves adding dependencies to the `stack.yaml`, making the project use `hpack`, adding dependencies to `package.yaml` and some more stuff, so it is not really straightforward.

**Comment by mdibaiee** [comment]
@NickSeagull alright, I will work on the button and empty folder part in the following days, will let you know :grin:

**Comment by NickSeagull** [comment]
Thanks @mdibaiee 🙏

**Comment by mdibaiee** [comment]
@NickSeagull alright so I was working on this, got the buttons and stuff ready, but about the input we want to show and prompt for the folder name, I thought we would want a prompt dialog, what do you think? And if so, how would we go about it's state and stuff?

**Comment by NickSeagull** [comment]
@mdibaiee yeah a prompt dialog would be great! About the state, hmm, we can just make a `projectName :: String` field in either `Toolbar.State` or `Compilation.State`

**Comment by mdibaiee** [comment]
Solved in #102
