### ISSUE TITLE
File explorer tries to open project even when path doesn't exist

### ISSUE THREAD

**Issue by vertexcite** [theam/haskell-do#101]
If I have an existing project in a folder, and I try to create a new project as a sibling with a name that starts with the name of the existing project, the file explorer treats the new path as if it were an existing project.
e.g. in `/home/me/projects/` there is a `project1` project.  
Open file explorer, navigate to `projects` start typing `project1a` (i.e. aiming so that path is `/home/me/projects/project1a`
It's in the new project state until the `1` is typed, then it switches to open project state, and stays that way even after typing the `a`.

**Comment by mdibaiee** [comment]
@NickSeagull this issue, as is described by vertexcite is fixed, but now, if you enter a directory name that does not exist manually (without choosing it by the file manager), there is no error thrown, and neither is the directory created, nothing happens.

What do you think we should do about it? I'd say we create the directory and initiate a project inside if the directory does not exist 🤔

**Comment by NickSeagull** [comment]
That would be a solution. Another one would be to make the text input read only, what do you think?

**Comment by mdibaiee** [comment]
@NickSeagull I think that is limiting flexibility, a user might want to copy paste a location to the input (specially if it's a long one). I'll create a PR for that.

**Comment by NickSeagull** [comment]
Thank you! Closing 🙏
