### ISSUE TITLE
Have a way of toggling the error box

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#104]
Right now, it is, well, um, unusable:

![image](https://user-images.githubusercontent.com/7448243/27448286-32f2f622-577c-11e7-98b6-44a783eeff68.png)

Maybe it would be good to have another button on the toolbar.

**Comment by mdibaiee** [comment]
@NickSeagull after the discussion on Gitter, do you think we could set a max-height of 10 - 50 percent of the height, and as we already leave some space at the bottom of the page, it should be OK, but we can also have a way of toggling it, would like to hear your thoughts, then I will work on it :grin:

**Comment by NickSeagull** [comment]
Yeah, sounds great! 😁 40% sounds cool

**Comment by mdibaiee** [comment]
@NickSeagull I think we can close this now
