### ISSUE TITLE
Autosave each X seconds and compile, not on each keypress

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#111]
We're autosaving on each keypress, making the file to be accessed too many times, exhausting it and making the performance much worse.

**Comment by mdibaiee** [comment]
@NickSeagull I would suggest instead of saving on intervals of time, we save with a [`debounce`](https://lodash.com/docs/4.17.4#debounce) on keypress.
So that would be triggered whenever the user stops writing code, then it makes sense to save and is safe. What do you think?

I can work on it once we reach a consensus :grin:

**Comment by NickSeagull** [comment]
Sounds great!

**Comment by mdibaiee** [comment]
@NickSeagull: I was working on this and noticed that the `State` types derive `Show` and `Read`, is it really necessary? Because for this `debounce`, I have to save a debounced action somewhere to call it every time which has type `IO (IO ())`, any suggestions?

**Comment by NickSeagull** [comment]
Hmmm, `transient` uses `Show` and `Read` for it's internal transport stuff. I was thinking about using `setRState` and `getRState` which are basically mutable references. [docs](https://hackage.haskell.org/package/transient-0.5.9.1/docs/Transient-Base.html#v:getRState)

**Comment by mdibaiee** [comment]
@NickSeagull: You are right, `Show` and `Read` are necessary.

I tried using `setRState` and `getRState` but it seems their value is not shared among different requests made to `update`, so everytime I call `getRState` again, I get an empty value.

We need a way to share a value between calls to `update` so we can know that there has already been a request and a write action should not be triggered 🤔  Any idea how such a shared value can be implemented?

**Comment by NickSeagull** [comment]
(Copying from gitter)
I think that debounce is good, but for simplicity sake I think it is better to just add a `lastSaveTime` field to the editor's `State` and on each keypress do 
```
when ( currentTime - lastSaveTime > interval ) $ do
    save
    state { lastSaveTime = currentTime }
```
It's much easier and less time consuming 😁

**Comment by mdibaiee** [comment]
@NickSeagull hmm, but this way, if a user types something within the interval, only his first keystroke will be saved and no more 🤔

**Comment by NickSeagull** [comment]
Theorically, with each keystroke, [the content of the editor is retrieved](https://github.com/theam/haskell-do/blob/master/src/common/HaskellDo/CodeMirror/View.hs#L40)

**Comment by mdibaiee** [comment]
@NickSeagull Yeah, but the way this save every X seconds works is, if I start typing something, and it takes 2 seconds, while the interval is 3, the first keystroke will trigger a save, but the other keystrokes will not pass the criteria of saving (being 3 seconds apart from the last keystroke), so they are not saved.

**Comment by NickSeagull** [comment]
Perhaps another possibility is to debounce saving in the core by hooking up ` local .` [`oneThread`](https://www.stackage.org/haddock/lts-9.0/transient-0.5.8/Transient-Base.html#v:oneThread) ` . liftIO` instead of [ `localIO` ](https://github.com/theam/haskell-do/blob/master/src/common/HaskellDo/Compilation/State.hs#L47) for saving and add a `threadDelay interval` ?

**Comment by mdibaiee** [comment]
@NickSeagull Sorry, I'm not sure I'm following you. How does `oneThread` help with the situation? I mean, how does it differ from doing a `localIO threadDelay`?

**Comment by NickSeagull** [comment]
Theorically it kills the previous thread that was scheduled for that task, so if the thread is still waiting it gets killed, and if it's not running, it spawns a new one 😄 

_(PS: Again, theorically, I haven't tested this approach)_

**Comment by mdibaiee** [comment]
@NickSeagull Aha, but it doesn't work, I'm not sure how or why, but it seems the calls to `_update` are _independent_ in some way, they do not share state, and now it seems, they do not share thread either

**Comment by NickSeagull** [comment]
Uuuh, then I think that we can do the save approach, even if some data is lost. We can make the contents to be saved when compilation is triggered tho

**Comment by mdibaiee** [comment]
@NickSeagull This can be closed as well :+1:
