### ISSUE TITLE
Unable to open stack Haskell project.

### ISSUE THREAD

**Issue by pamu** [theam/haskell-do#129]
Unable to open stack Haskell project

error:

Command-line `haskell-do` prints "connection closed" endlessly 
```
listen websocket:ConnectionClosed
listen websocket:ConnectionClosed
listen websocket:ConnectionClosed
listen websocket:ConnectionClosed
listen websocket:ConnectionClosed
```

**Comment by NickSeagull** [comment]
Hello! Are you creating a new project with Haskell.do or opening an existing one? If its the latter, Haskell.do only supports projects that have been created with it. :smile: 

Thanks for reporting!

**Comment by NickSeagull** [comment]
Closing as no information was provided
