### ISSUE TITLE
haskelldo-core: user error

### ISSUE THREAD

**Issue by mimi1vx** [theam/haskell-do#13]
mimi@argusek ~/haskell-do/core (master) $ stack exec haskelldo-core
haskelldo-core: user error (Pattern match failure in do expression at app/Main.hs:16:3-14)

**Comment by NickSeagull** [comment]
What are you trying to accomplish? @mimi1vx 😄

**Comment by SamuelSchlesinger** [comment]
Thank you for this report @mimi1vx. This is a poorly documented but easily discoverable behavior of core/app/Main.hs: it takes a filepath which will be the output of your HaskellDO session. This issue can be closed then? Unless someone think this behavior needs to be documented somewhere more clearly, or a proper error message issued..

**Comment by ocramz** [comment]
@SamuelSchlesinger @NickSeagull even a default filepath would suffice, though it depends on the user's layout. Otherwise the user guide should make it clear that the user is not supposed to run `haskelldo-core` by hand

**Comment by mimi1vx** [comment]
@NickSeagull  this https://github.com/theam/haskell-do#running-in-dev-mode

**Comment by NickSeagull** [comment]
@mimi1vx that is true, we should not support that. That's the old way of running in dev mode. Gonna remove it right now. Closing this issue
