### ISSUE TITLE
Websockets server needs to change

### ISSUE THREAD

**Issue by SamuelSchlesinger** [theam/haskell-do#14]
This is the note under "runServer", which we are currently using for our only backend, in the websockets package:

> 
> Provides a simple server. This function blocks forever. Note that this is merely provided for quick-and-dirty standalone applications, for real applications, you should use a real server.
> 
> Glue for using this package with real servers is provided by:
> 
> https://hackage.haskell.org/package/wai-websockets
> https://hackage.haskell.org/package/websockets-snap
> 

Clearly this is not what we should be using and thus I'm going to begin a fix on this presently.

**Comment by SamuelSchlesinger** [comment]
#15 has been born

**Comment by o1lo01ol1o** [comment]
Just a note: jupyter runs on a zmq server; setting up a zmq server via node with a haskell took all of 30 minutes when I played with electron.  Performance will likely be better than websockets as well.

**Comment by SamuelSchlesinger** [comment]
I like that @o1lo01ol1o but it doesn't seem justifiable to me if it would impose significant changes in code, as performance up to right now hasn't really not a major concern. I do think its a better design point though and should be explored now if possible or in the future. Maybe we could make a separate issue about it and keep an eye on the idea?

**Comment by kitfre** [comment]
Resolved with merge of #15 !
