### ISSUE TITLE
ZMQ Backend

### ISSUE THREAD

**Issue by o1lo01ol1o** [theam/haskell-do#16]
This more of a post-it note, but as noted in #14, zmq offers another performant backend for message transport between server and frontend.  This use case may only be needed in oscilloscopes and the like, but, hey, oscilloscopes are cool.

**Comment by SamuelSchlesinger** [comment]
Is this something we should now look into after having problems with the attempt to use Servant? @KitFreddura @NickSeagull

**Comment by NickSeagull** [comment]
Remember that we are going to drop PS in favor of GHCJS, also. ZMQ does not have browser connectors AFAIK @SamuelSchlesinger

**Comment by NickSeagull** [comment]
We now use Transient, which does all transport and serialization transparently, closing this :)
