### ISSUE TITLE
Text edior integration?

### ISSUE THREAD

**Issue by AnthonyJacob** [theam/haskell-do#17]
Is it possible to integrate this functionality into Visual Studio Code?

**Comment by NickSeagull** [comment]
Hey @AnthonyJacob ! Thanks for opening an issue. What do you mean exactly? ^^

**Comment by AnthonyJacob** [comment]
What I always hate about jupyter was the fact it was only available in the browser.

From my understanding you have built your own IDE for your project based on electron which is definitely step in the right direction.

But I am unsure what is your vision of project. Is it supposed to be an IDE or just a text editor on steroids (like atom, sublime text or visual studio code)? 

In case of IDE it is completely understandable it is shipped as a standalone application. 

In case of text editor not so much unless the features show up to be worth another installation. For example I am using spacemacs and visual studio code (moved from sublime and atom) as an text editor right now and I am not looking forward installing yet another similar application. 

Therefore I was wondering whether the functionality couldn't be provided trough a package in some already established electron based text editor.

**Comment by NickSeagull** [comment]
Hello @AnthonyJacob , our goal is to build a standalone IDE. Right now the features are kinda basic, but in the future there will be better ones.

I hate using Jupyter from the browser too, but by incorporating this into an existing text editor we would lose many possibilities of extending the GUI itself. 😄

**Comment by NickSeagull** [comment]
Closing as it is not aligned withe project goals right now.
