### ISSUE TITLE
Removing dialog on close keeps Windows from killing process

### ISSUE THREAD

**Issue by kitfre** [theam/haskell-do#23]
Hey guys,

So HaskellDO exits properly now, as long as we keep that closing dialog box. But removing that dialog box causes the process to keep running after close, which is super bizarre. I've tried a bunch of things to no avail, so if anyone has any suggestions or wants to mess around with it please do!

Resolving this resolves #7 

Edit: The dialog in question is in `Main.js` in `gui/dist` under `mainWindow.on('close')`

**Comment by NickSeagull** [comment]
This is fixed now.
