### ISSUE TITLE
Port PureScript + Electron to GHCJS

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#3]
I think that Electron could be changed to a thin Haskell layer that just opens and closes system dialogs, the frontend would pass ADTs to the backend as actions to the backend process through a websocket, making the interconnection seamless.

Right now what we have is something like this:

![current architecture](https://cloud.githubusercontent.com/assets/7448243/22548564/e65b3a78-e93e-11e6-8129-e48bb6f44cbf.png)

The thing with this is that we are duplicating responsibilities by having Electron and the Haskell core at the same time. Electron actually has two processes, a chromium renderer, which is the one that renders the PS site, and the NodeJS backend which is the one that spawns the Haskell core and interoperates with the current operating system. This shouldn't be hard to do with conditional compilation.

The ideal architecture would be:
![ideal architecture](https://cloud.githubusercontent.com/assets/7448243/22549034/39ec15f2-e941-11e6-9bf6-c93fde02404d.png)

I imagine having something like the **Elm** architecture (which we currently have in the frontend) but for the whole application. The `view` would be in the GHCJS part, the `update` in the Haskell Core, and the `appState` would be in a common module that's shared between `view` and `update` along with implicit serialization/deserialization and sending.

I think this could be even a game changer for writing desktop apps in Haskell

**Comment by tonyday567** [comment]
Without having looked at the code, I would suggest that the ideal structure is:

GHCJS Events -> Haskell Core -> GHCJS Render

Busting that loopiness, and fully separating what is an action or event (a controller), from what is a view brings complexity way down.

I'm a big fan of the [mvc](https://github.com/Gabriel439/Haskell-MVC-Library) library and the general concept which @Gabriel439 blogs about here: http://www.haskellforall.com/2014/04/model-view-controller-haskell-style.html. It hasn't seen much love over the years, but has the potential to help with the game-changing.

**Comment by NickSeagull** [comment]
@tonyday567 That's in fact the idea about the structure. The point that would sell a lot would be to have a framework that resembles Elm, or `purescript-pux`. Looking at the GitHub stars and the Twitter activity, lot of people that liked this project are Elm and PS people, it would help them a lot to contribute if they had something like Elm to work with. 😄

**Comment by NickSeagull** [comment]
Done! Closing
