### ISSUE TITLE
make build-all-linux fails

### ISSUE THREAD

**Issue by jluttine** [theam/haskell-do#35]
I'm still new to Haskell and Stack. I just tried to install this package following the instructions, but I got an error on `make build-all-linux`:

```
To install the correct GHC into /home/jluttine/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

I tried `stack setup`:
```
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```

But I still get the original error after this. Any ideas what to do? I'm a bit lost here..

**Comment by vlastachu** [comment]
```
cd core
stack setup
```
just guess

**Comment by SamuelSchlesinger** [comment]
Try what @vlastachu said and if it doesn't work let us know please. If you haven't already, you should run "make deps"

**Comment by vlastachu** [comment]
@SamuelSchlesinger  Btw I don't see `stack setup` in Makefile. How stack ghc should be installed?

**Comment by jluttine** [comment]
Thanks @vlastachu, that solved the issue!

**Comment by SamuelSchlesinger** [comment]
Not sure @vlastachu, intuitively I'd think it would be a part of "make deps"... @NickSeagull @KitFreddura

**Comment by NickSeagull** [comment]
Gonna add this to the Makefile
