### ISSUE TITLE
Console not working / empty

### ISSUE THREAD

**Issue by jluttine** [theam/haskell-do#36]
No idea if I'm just doing something wrong here but the console panel is just empty grey rectangle with nothing in it. I can click a mouse at the top of it to get an input text field there and I can write text there but nothing happens, no matter how many times I press Enter. In the README instructions, there's at least `>` symbol visible but I don't have even that. Any ideas?

**Comment by kitfre** [comment]
The `>` not being there when you open the console for the first time is okay, I got rid of that as it was causing an error in the console but I'll put it back soon!

As per the rest of the issue, can you give me some details as to how you're launching HaskellDO? I.e what are you trying to edit, is it a new file or an old one, etc? Thanks!

**Comment by NickSeagull** [comment]
Exactly, I think that we should send a "Save" message automatically when toggling it. Also another thing that might happen @jluttine is that you've never run `stack repl` inside the project you've created. HaskellDO has some issues right now for managing the part of the build when `stack` download dependencies

**Comment by jluttine** [comment]
I'm just trying to follow the steps in https://github.com/theam/haskell-do#usage

After `make build-all-linux`, I created a new project `stack new my_project` to another directory location. Then, I came back to haskell-do directory and ran `make run` at the root of that directory. The guide says: `Navigate to the root of the project you just created and open that folder.` But I wasn't able to open a folder, I needed to select a file. So I just chose the only Haskell file in that directory: `Setup.hs`. It didn't show any content for that file although there are a few lines of code if I check using a text editor. Also, saving doesn't write anything to that file. And the console is just empty and non-working as I described before.

I tried running `stack repl` at `my_project` folder but it didn't work, I had to run `stack setup` first, then `stack repl` worked. Then, I went back to `haskell-do` folder and ran `make run` but none of the issues disappeared.

**Comment by kitfre** [comment]
Hmm okay. There has been an update to HaskellDO so know you can edit any file, not just a stack project so I'll update the README accordingly. Can you try running `stack build` in the project and then try launching HaskellDO again? If that doesn't work, please let me know and I'll look around and see what could be causing your issues.

**Comment by jluttine** [comment]
I updated my haskell-do repo and re-ran the installation steps. I also ran `stack build` under my project root directory. Still not working. Some details:

The instructions say:

> Fire up HaskellDO by running `make run` from the root of the project

But there's no Makefile in my project.. I created my project as `stack new your_project_name` (not under haskell-do directory, but elsewhere) as told in the instructions and it doesn't create any Makefile there.

So I'm running `make run` in haskell-do root. And then I open `Setup.hs` file from the root of my project directory and I have the issues I've described.

**Comment by NickSeagull** [comment]
You're absolutely right @jluttine, the README explains itself poorly.
You are right when you open Haskell do with make run.

After that open src/Lib.hs instead of Setup.hs, tell me how it goes.

Thanks for your feedback, youre awesome 😉

**Comment by jluttine** [comment]
Ok, thanks! I opened src/Lib.hs (under my project directory) but still the same issues.

**Comment by NickSeagull** [comment]
Could you try running `stack build` from the root of your project and tryig again @jluttine?

**Comment by jluttine** [comment]
I did run it already before trying. Here's the output I got then:
```
$ stack build
haskell-do-test-0.1.0.0: unregistering (local file changes: README.md)
haskell-do-test-0.1.0.0: build (lib + exe)
Preprocessing library haskell-do-test-0.1.0.0...
Preprocessing executable 'haskell-do-test-exe' for haskell-do-test-0.1.0.0...
haskell-do-test-0.1.0.0: copy/register
Installing library in
/home/jluttine/Workspace/haskell-do-test/.stack-work/install/x86_64-linux-ncurses6/lts-8.5/8.0.2/lib/x86_64-linux-ghc-8.0.2/haskell-do-test-0.1.0.0-BrKLoxVgO8S6RTyFQheKmn
Installing executable(s) in
/home/jluttine/Workspace/haskell-do-test/.stack-work/install/x86_64-linux-ncurses6/lts-8.5/8.0.2/bin
Registering haskell-do-test-0.1.0.0...
```

(I had to run `touch README.md` before that, otherwise `stack build` failed.)

**Comment by jluttine** [comment]
Just FYI, I'm new to Haskell so I don't really know very well what I'm doing and I may have missed something that should be very obvious for any haskeller.

**Comment by jluttine** [comment]
For completeness, here are the exact steps to reproduce the issue:

```
cd /tmp/
git clone https://github.com/theam/haskell-do
cd haskell-do/
make deps
cd core
stack setup
cd ..
make build-all-linux
cd ..
stack new project
cd project
stack setup
stack repl
:q
stack build
cd ../haskell-do
make run
```

Now open `/tmp/project/src/Lib.hs` and at least I can see the issues I've described:

- No content shown for the file although it really has content

- Console panel is empty and doesn't do anything. I can only activate an input text field at the top and write some text there but nothing else happens no matter what I've tried.

- Saving the file doesn't write anything to the file.

**Comment by NickSeagull** [comment]
Thanks for detailing that much. It absolutely okay that you are not that familiar with Haskell. As the target audience of Haskell Do is not just Haskell users but also Data Scientists.

There is a bug, where sometimes, when closing Haskell Do, the core is still left running. Could you check if there's a process called haskelldo-core something and kill it?

When that happens, the issues that appear are exactly what you described.

Thanks @jluttine

**Comment by jluttine** [comment]
Didn't seem to be running:
```
$ ps ax | grep haskelldo
 9703 pts/3    S+     0:00 grep haskelldo
$ make run
```
But still the same issues

**Comment by NickSeagull** [comment]
Try `grep haskell-do`

**Comment by jluttine** [comment]
Just plain `haskell`:
```
$ ps ax | grep haskell
21780 pts/3    S+     0:00 grep haskell
$ make run
```
And still the issues.

Anyone else able to reproduce the issue with the steps I gave?

**Comment by NickSeagull** [comment]
I'm on Windows right now, as I'm on my laptop travelling. Will try as soon as I get home to do so on Linux

**Comment by NickSeagull** [comment]
@jluttine this should be fixed by now, the README is updated and Haskell.do should work fine when opened at least twice. Could you try now? Thanks! 😄

**Comment by jluttine** [comment]
Yep. Seems to work now. Thanks! And btw, I like how the console evaluates only one expression and "resets" after every evaluated expression. 👍
