### ISSUE TITLE
Can't open folder on start

### ISSUE THREAD

**Issue by meownoid** [theam/haskell-do#39]
When starting, file choosing dialog appears, but I'm able to choose only `.hs` files, not folders. Tried on latest version from git.
![screenshot_20170317_220215](https://cloud.githubusercontent.com/assets/20129246/24058861/ba250a42-0b5d-11e7-8c91-d2da56677dc4.png)

**Comment by NickSeagull** [comment]
Yes, we have to change that in the README, #36 mentions this too.

Open `src/Lib.hs`

Thanks for reporting the issue! 😄

**Comment by kitfre** [comment]
There has been an update to HaskellDO. In the original release you could only edit `Main.hs`,so we just had you select a folder. Now you can edit any Haskell file on your system so we've switched to selecting files. We will update the README to clear up the confusion, thanks!

**Comment by NickSeagull** [comment]
The README is updated now, so this should be closed
