### ISSUE TITLE
Make "error 64" after succesfully building OSX backend

### ISSUE THREAD

**Issue by ocramz** [theam/haskell-do#5]
```
haskelldo-core-0.1.0.0: copy/register
Installing executable(s) in
/Users/.../haskell-do/core/.stack-work/install/x86_64-osx/lts-7.14/8.0.1/bin
Completed 67 action(s).
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
make: *** [build-back-osx] Error 64
```

**Comment by NickSeagull** [comment]
Seems like the `cp` comand from the osx target was not executing correctly, just fixed it in the [latest commit](https://github.com/theam/haskell-do/commit/7143c708915638b8189e5bf18e92b3fd621cca58), can you confirm?

**Comment by NickSeagull** [comment]
@ocramz Does this thing keeps happening with the new `Makefile`?

**Comment by ocramz** [comment]
I'm really puzzled. The commands work when run individually, but not from makefile.

When I run `make build-back-osx`, the `$(stack path .. )` command is simply erased, and obviously it can't find the binary in the wrong path. This is what gets echoed on terminal:

```
cd core &&\
		stack build &&\
		cp /bin/haskelldo-core ../gui/dist/bin/haskelldo-core-darwin
cp: /bin/haskelldo-core: No such file or directory
```

**Comment by NickSeagull** [comment]
@ocramz, please, could you try modifying the command in the Makefile and writing it in backticks like
```bash
`stack path ..`/bin/...
```
?

**Comment by ocramz** [comment]
Yep, this works!

So this should be the recipe:

```
build-back-osx:
	cd core &&\
		stack build &&\
		cp `stack path --local-install-root`/bin/haskelldo-core ../gui/dist/bin/haskelldo-core-darwin
		cd ..
```
