### ISSUE TITLE
File explorer for "Open project"

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#59]
It would be nice to have a file explorer instead of that ugly text input we have 😄

**Comment by mdibaiee** [comment]
@NickSeagull after some search, it seems there is only a non-standard way of having a "directory" input, and that is by using `webkitdirectory` attribute ([supported by Chrome, Firefox, Safari and Microsoft Edge](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory)), seems to be our best shot, if you agree on using this, I can work on this :+1: :grin:

**Comment by NickSeagull** [comment]
I was checking it out, the problem that I ser there is that it just gives us the relative path, starting from the directory that the user selected. We need the absolute one. What about getting a tree using `System.Directory` and then just showing it?

**Comment by mdibaiee** [comment]
@NickSeagull woops, even worse, I just found out it doesn't work on empty directories, definitely not an option anymore. So yeah, I guess fetching the tree from server-side makes sense, can I start working on it? :grin:

**Comment by NickSeagull** [comment]
Of course! Thank you!!

**Comment by mdibaiee** [comment]
@NickSeagull guess this one's done now, can close :grin: :+1:

**Comment by NickSeagull** [comment]
Yep! Thanks 😄
