### ISSUE TITLE
stack path is hardcoded to be /usr/local/bin/stack

### ISSUE THREAD

**Issue by mdibaiee** [theam/haskell-do#60]
Hey,

I could not create a new Haskell.DO project, and by reading logs I found out that `stack` is assumed to be in `/usr/local/bin/stack`, while mine is somewhere else.

Steps to reproduce:

1. Install stack anywhere except `/usr/local/bin`, e.g. `~/.local/bin`
2. Start haskell-do
3. Try to create a new project
4. It will fail silently (on the client-side) and print out a long indicating the command executed: 
```
Executing: cd /some/path && /usr/local/bin/stack new do https://raw.githubusercontent.com/theam/stack-templates/master/haskell-do-new.hsfiles
```

~~(I'm working on a pull-request, setting up my environment right now :grin: :+1:)~~
See #62

**Comment by NickSeagull** [comment]
Nice, thanks Mahdi! 😄

**Comment by NickSeagull** [comment]
I guess this can be closed now! 😄
