### ISSUE TITLE
Core is left running when closing the GUI

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#7]

**Comment by SamuelSchlesinger** [comment]
Essentially this is the fault of the current websocket server we're using and I don't believe there is a reasonable way to stop it without changing that piece of the design.

**Comment by SamuelSchlesinger** [comment]
This may be fixed after #15 is merged? If so we can close this and #14 at once!

**Comment by kitfre** [comment]
Fixed with merge of #15 !

**Comment by kitfre** [comment]
This works on Windows only sometimes, half the time it exits gracefully for me, but the other half it hangs. It seems to be fixed totally on Linux and MacOS though. I've seen some issues online where processes spawned by npm on windows tend to spawn a lot of child processes.

**Comment by NickSeagull** [comment]
Weird thing, this may be fixed with #3

**Comment by NickSeagull** [comment]
Irrelevant with new version, closing
