### ISSUE TITLE
When clicking on project settings, server crashes

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#78]
Looks like the path is being written incorrectly:

<img width="1053" alt="captura de pantalla 2017-06-09 a las 16 53 49" src="https://user-images.githubusercontent.com/7448243/26981049-4c8abedc-4d34-11e7-81fe-a7055a73c38e.png">

Pinging @mdibaiee

**Comment by mdibaiee** [comment]
@NickSeagull Are you sure you are on the latest commit? I guess this was addressed in https://github.com/theam/haskell-do/commit/f5c77bc1cda381790087f56f38f93e2bab33050f, otherwise let me know and I'll see (I couldn't find anything by skimming through the code :grin:)

**Comment by NickSeagull** [comment]
False alarm @mdibaiee had to remove `.stack-work` and rebuild lol
