### ISSUE TITLE
Trailing character of new project truncated

### ISSUE THREAD

**Issue by vertexcite** [theam/haskell-do#80]
The path for a new project must end with a trailing slash.
If not, the last character is truncated for what actually happens on the filesystem, but the UI tries the non-truncated name and says it can't find the project.

**Comment by NickSeagull** [comment]
Pinging @mdibaiee :)

**Comment by mdibaiee** [comment]
@vertexcite could you please paste haskell-do's logs? :grin:
also see if #78 is relevant to your issue (try removing `.stack-work` and re-building with the latest version)

**Comment by NickSeagull** [comment]
@mdibaiee two users at Zurihac tried to do the same and it happened too to them D:

**Comment by mdibaiee** [comment]
@NickSeagull: solved in #99 :grin: :+1:

**Comment by NickSeagull** [comment]
Closing!
