### ISSUE TITLE
Render flashes when pressing a key

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#83]
I suspect that this happens because we are updating all the widgets, what do you think @mdibaiee ?

**Comment by mdibaiee** [comment]
@NickSeagull yeah, I had noticed that, everytime any action is triggered, everything in `updateDisplays` is re-rendered.

An idea just hit me: what if we pass the old, and the new state to `updateDisplays`, and the functions inside check whether they should actually trigger a re-render for a specific view? It's a little dirty still, but can be a ground for better ideas :grin:, let me know what you think

**Comment by NickSeagull** [comment]
I was talking to @pkapustin at Zurihac about this issue and maybe we could implement a VirtualDOM like Elm does within `Ulmus.hs`, what do you think @mdibaiee ? It might even make everything easier, so no need to have the overhead of "what do I have to update?"

**Comment by mdibaiee** [comment]
@NickSeagull yep, of course, that's a good solution, though might be a little tricky :+1: :grin:

**Comment by NickSeagull** [comment]
Solved with a hotfix
