### ISSUE TITLE
Make Makefile autocheck the platform

### ISSUE THREAD

**Issue by NickSeagull** [theam/haskell-do#9]
One could check so with environment variables or `uname -s`.

**Comment by kitfre** [comment]
Created a new branch `makefile-check` with a start towards this. Note that Windows users who run `Cygwin` will run into issues

**Comment by NickSeagull** [comment]
@KitFreddura, I just discovered [Shake](http://shakebuild.com/manual) a build system by @ndmitchell. We can definitely switch to it.
